# Change these first
owner: rackerlabs # Your GitHub organization or username, where this repository lives
repo: rs-flex-uptime # The name of this repository

sites:
  - name: nova-api
    url: https://nova.api.sjc3.rackspacecloud.com
  - name: neutron-api
    url: https://neutron.api.sjc3.rackspacecloud.com
  - name: keystone-api
    url: https://keystone.api.sjc3.rackspacecloud.com/v3
  - name: octavia-api
    url: https://octavia.api.sjc3.rackspacecloud.com
  - name: glance-api
    url: https://glance.api.sjc3.rackspacecloud.com
  - name: heat-api
    url: https://heat.api.sjc3.rackspacecloud.com
  - name: cinder-api
    url: https://cinder.api.sjc3.rackspacecloud.com
  - name: cloudformation-api
    url: https://cloudformation.api.sjc3.rackspacecloud.com
  - name: placement-api
    url: https://placement.api.sjc3.rackspacecloud.com
  - name: barbican-api
    url: https://barbican.api.sjc3.rackspacecloud.com
  - name: magnum-api
    url: https://magnum.api.sjc3.rackspacecloud.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.api.sjc3.rackspacecloud.com
  #baseUrl: /rs-flex-uptime
  logoUrl: https://docs.rackspacecloud.com/assets/images/rackspace_logo-white.svg
  favicon: https://docs.rackspacecloud.com/assets/images/pngegg.png
  themeUrl: https://status.api.sjc3.rackspacecloud.com/flex.css
  name: Rackspace Flex Cloud
  introTitle: "Flex API Status"
  #introMessage:
  navbar:
    - title: Status
      href: /
    - title: Genestack GitHub
      href: https://docs.rackspacecloud.com
    - title: Rackspace
      href: https://rackspace.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
