# Change these first
owner: the2hill # Your GitHub organization or username, where this repository lives
repo: rs-flex-uptime-dfw # The name of this repository

sites:
  - name: nova-api
    url: https://nova.api.dfw3.rackspacecloud.com
  - name: neutron-api
    url: https://neutron.api.dfw3.rackspacecloud.com
  - name: keystone-api
    url: https://keystone.api.dfw3.rackspacecloud.com/v3
  - name: glance-api
    url: https://glance.api.dfw3.rackspacecloud.com
  - name: octavia-api
    url: https://octavia.api.dfw3.rackspacecloud.com
  - name: heat-api
    url: https://heat.api.dfw3.rackspacecloud.com
  - name: cinder-api
    url: https://cinder.api.dfw3.rackspacecloud.com
  - name: cloudformation-api
    url: https://cloudformation.api.dfw3.rackspacecloud.com
  - name: placement-api
    url: https://placement.api.dfw3.rackspacecloud.com
  - name: barbican-api
    url: https://barbican.api.dfw3.rackspacecloud.com
  - name: magnum-api
    url: https://magnum.api.dfw3.rackspacecloud.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.api.dfw3.rackspacecloud.com
  #baseUrl: /dfw-rs-flex-uptime
  logoUrl: https://docs.rackspacecloud.com/assets/images/rackspace_logo-white.svg
  favicon: https://docs.rackspacecloud.com/assets/images/pngegg.png
  themeUrl: https://status.api.dfw3.rackspacecloud.com/flex.css
  name: Rackspace Flex Cloud
  introTitle: "Flex API Status"
  #introMessage:
  navbar:
    - title: DFW Status
      href: /
    - title: SJC Status
      href: https://status.api.sjc3.rackspacecloud.com
    - title: Docs
      href: https://docs.rackspacecloud.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
